name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Or a more recent stable version like v4
    - name: Set up Python
      uses: actions/setup-python@v3 # Or a more recent stable version like v4 or v5
      with:
        python-version: '3.10' # Match the project's Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-mock # Ensure testing tools are installed
    - name: Test with pytest
      run: |
        export PYTHONPATH=.
        pytest tests/unit/
